eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    #https://github.com/ExampleDriven/spring-cloud-eureka-example/blob/master/customer-service/src/main/resources/application.yml

    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 1
server:
  port: 8091
spring:
  application:
    name: movie-catalog-service

# Disable Hystrix timeout globally (for all services)
hystrix.command.default.execution.timeout.enabled: false

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false